Cap’n Proto and FlatBuffers  are high performance serialization libra…
rsocket/rsocket pull request #314
Opened 2020-10-25 17:56 UTC by linux-china

…ry, and they should be included in WellKnownType, and especially useful to per stream DataMimeType, and text MimeType is too long for them because of performance.

2020-10-25 18:57 UTC, yschimke commented
No strong opinion. Just a typo

2020-10-25 18:57 UTC, yschimke requested changes

2020-10-25 18:57 UTC, yschimke commented on Extensions/WellKnownMimeTypes.md
> +| `application/application/x-capnp` | `0x29`
Doubled up?

2020-10-25 19:14 UTC, linux-china commented on Extensions/WellKnownMimeTypes.md
> +| `application/application/x-capnp` | `0x29`
sorry, my bad. fixed.

2020-10-25 20:49 UTC, yschimke commented
These don't seem like well known mime types. Any precedent for them? Not a blocker, just want to understand, including whether it actually works for flatbuffer or you also need to specify some extended form for you particular domain.

2020-10-25 21:37 UTC, linux-china commented
@yschimke  yes, they are not wellknown mime type, and they don't have formal MimeType name yet.   FlatBuffers is some popular, and it's successor of Protobuf. The flatbuffers is used in Deno now.    Cap’n Proto is not popular too, and it's an 
 alternative for Protobuf because of high performance.   Both are very popular in Rust ecosystem because of performance.  Now we use both of them with Rust + RSocket to transfer binary data because of performance consideration.   RSocket is high performance binary protocol, and we think we should add some hign performance serialization library support.  For example, in the case of per stream data type, if we use 'application/x-flatbuffers'  text name, and it's not good for high performance scenario,  mimetype text name should be include in metadata to make payload bigger, and you should parse text mime type name, and text is not good for good for performance.  If both mimetypes in WelllknownMimeType, and just 1 byte to the mime type, size and parsing are all good for high performance system.

2020-10-26 12:06 UTC, OlegDokuka commented
@linux-china can we just stick to flatbuffer. Flatbuffer makes sense to include in standard well-known-mime-types, but Cap’n Proto does not sound like something anybody would use in the long-term perspective so it would just withhold one id for it.

> RSocket is high performance binary protocol, and we think we should add some hign performance serialization library support.

I guess in that case support means "being able to use X", I don't think there are any prevention points to start using flatbuffer and Cap’n Proto without having them in the wellknownmimetypes. We have support for custom metadata, so it should not be an issue to encode those mimes as a string.

Though, I'm ok with adding that types to well know I don't see them as a commonly used (at least the Cap’n Proto one)

2020-10-26 19:01 UTC, yschimke commented
@OlegDokuka at least these aren't likely to spiral out of control, the cardinality seems fixed. I'd be inclined to err on side of just allowing, and if anyone objects, we can firm up the policy.  But I'll defer.

2020-11-02 17:14 UTC, simonbasle commented
@OlegDokuka my 2 cents: I think this request makes sense, especially since `WellKnownType` are there for squeezing more efficiency out of the protocol (and these 2 serialization formats have the same efficiency and performance goals). I've been looking at Cap-n-Proto in the past and I think it is an interesting project, started by the creator of protobuffers v2 (one needs to look past the goofy name though :smile:). it is probably true that it is way less popular / known though (vs a google-backed product)

2020-11-02 17:19 UTC, OlegDokuka commented
@simonbasle that sounds reasonable. Thank you for your opinion!

I will be just merging this one.

2020-11-02 17:19 UTC, OlegDokuka approved these changes
LGTM

2020-11-02 17:21 UTC, merged